channels:
  - conda-forge
dependencies:
  - python=3.8
  - econ-ark=0.12.0
  - numpy=1.20.1
  - matplotlib=3.3.4
  - seaborn=0.11.1
  - ipython
  - nbformat
  - ipywidgets
  - pip
  - pip:
    - EconModel==0.1
    - ConSav==0.1
